bindAddress: ":8080"

mongodb:
  uri: "mongodb://db_user:db_pwd@127.0.0.1:27017/books?retryWrites=true&w=majority&authSource=admin&maxPoolSize=20"
  database: books

redis:
  address: "localhost:6379"
  password: pwd
  db: 1
  poolSize: 10
  poolTimeoutSeconds: 30
  readTimeoutSeconds: 30
  writeTimeoutSeconds: 30

execution:
  web2:
    enabled: true
    parallel: true
    jobs:
      #下载单篇书籍
      - name: articleJob
        source: articleTopic
        destination: chapterTopic

      - name: chapter
        source: chapterTopic
  web1:
    enabled: true
    parallel: true
    jobs:
      - name: homeJob
        parser: HomeParser #HomeParser, CatalogParser, CatalogPageParser, BookParser, ChapterParser
        url: http://home.com
        destination: catalogTopic
        action:
          load: true
          save: true
          analyse: true

      - name: catalogJob
        source: catalogTopic
        destination: articlePage

      - name: articlePageJob
        source: articlePage
        destination: articleTopic

      - name: articleJob
        source: articleTopic
        destination: chapterTopic

      - name: chapter
        source: chapterTopic

logSetting:
  logLevel: DEBUG
  logPath: /var/log/myspider # 日志存放路径：${logPath}/${fileName}
  outputToConsole: true  # 是否同时将日志打印到控制台
  fileName: myspider.log
  maxSizeInMB: 100   # 日志文件的体积
  maxAgeInDay: 30   # 最多保留天数
  maxBackups: 10    # 允许存在几个日志备份文件
  compress: true    # 是否压缩保存历史文件