bindAddress: ":8080"

spider:
  httpProxy: http://localhost:10809

mongodb:
  uri: "mongodb://db_user:db_pwd@127.0.0.1:27017/books?retryWrites=true&w=majority&authSource=admin&maxPoolSize=20"
  database: books

redis:
  address: "localhost:6379"
  password: pwd
  db: 0
  poolSize: 10
  poolTimeoutSeconds: 30
  readTimeoutSeconds: 30
  writeTimeoutSeconds: 30

execution:
  web1:
    enabled: true
    parallel: true
    name: 第一版主小说网
    homeUrl: https://m.xinbanzhu.net/sort/
    jobs:
      #首页，确定有多少栏目
      - name: homeJob
        type: HomeJob
        parser: HomeParser #HomeParser, CatalogHomeParser,CatalogParser, CatalogPageParser, BookParser, ChapterParser

      # 每个栏目确定有多少页，每一页发送一条消息
      - name: catalogHomeJob
        type: CatalogHomeJob
        parser: CatalogHomeParser

      # 当前页下有多少书籍
      - name: catalogPageJob
        type: CatalogPageJob
        parser: CatalogPageParser

#      - name: articlePageJob
      #        source: articlePage
      #        destination: articleTopic

#      - name: articleJob
      #        source: articleTopic
      #        destination: chapterTopic

#      - name: chapter
#        source: chapterTopic

logSetting:
  logLevel: DEBUG
  logPath: /var/log/myspider # 日志存放路径：${logPath}/${fileName}
  outputToConsole: true  # 是否同时将日志打印到控制台
  fileName: myspider.log
  maxSizeInMB: 100   # 日志文件的体积
  maxAgeInDay: 30   # 最多保留天数
  maxBackups: 10    # 允许存在几个日志备份文件
  compress: true    # 是否压缩保存历史文件